services:
  ubuntu:
    image: amd64/ubuntu
    volumes:
      - ../:/HOST
    command: bash -c "
        apt-get update
        && apt-get -y install gcc
        && apt-get -y install zsh
        && apt-get -y install wget
        && apt-get -y install git
        && apt-get -y install libc6-dev
        && wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
        && tail -f /dev/null
      "